### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by ovizii** [fmbla/spamassassin-levenshtein#1]
Hi there,

just wondering what the purpose of the plugin is, do you think the levenshtein distance between sending/recipient domains could be a spamminess indicator?

**Comment by steadramon** [comment]
Yes this is the intention here. Also testing the from address for potentially close domains.

I intend to update this with a simple rule change to not capture freemail addresses like gmail.com and ymail.com

**Comment by ovizii** [comment]
hm, thanks for clarifying. will keep an eye on the project's progress.
